name: Anthony round 1
favicon: null
layout_spectrum: 0.3707477664574981
typography_spectrum: 0.7771913625765592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7174816231708974
  lightness: 0.5142385680228472
  saturation: 0.8427058001980186
  rhythmicContrast: 0.7482818157877773
purpose: []
